name: Anvil
version: "1.0.0-SNAPSHOT"
main: org.anvilpowered.anvil.bungee.plugin.AnvilCoreBungee
api-version: 1.13
authors: [Cableguy20, STG_Allen]
description: A cross-platform Minecraft plugin framework
website: https://anvilpowered.org
