name: Anvil
version: "0.1.2-SNAPSHOT"
main: org.anvilpowered.anvil.bungee.plugin.AnvilCoreBungee
api-version: 1.15
description: A cross-platform Minecraft plugin framework
website: https://anvilpowered.org
