name: Anvil
version: "1.0.0-SNAPSHOT"
main: org.anvilpowered.anvil.spigot.plugin.AnvilCoreSpigot
api-version: 1.13
authors: [Cableguy20, STG_Allen]
description: A cross-platform Minecraft plugin framework
website: https://anvilpowered.org
commands:
  anvil:
    description: Anvil root command
  callback:
    description: Anvil callback command
