name: Anvil
version: "0.1.3-SNAPSHOT"
main: org.anvilpowered.anvil.spigot.plugin.AnvilCoreSpigot
api-version: 1.15
description: A cross-platform Minecraft plugin framework
website: https://anvilpowered.org
commands:
  anvil:
    description: Anvil root command
  callback:
    description: Anvil callback command
