name: Anvil
version: "0.1.0-SNAPSHOT"
main: org.anvilpowered.anvil.nukkit.plugin.AnvilCoreNukkit
api: ["1.0.0"]
description: A cross-platform Minecraft plugin framework
website: https://anvilpowered.org
