name: Anvil
version: "0.4.0-SNAPSHOT"
main: org.anvilpowered.anvil.paper.AnvilPaper
api-version: 1.15
description: A cross-platform Minecraft plugin framework
website: https://www.anvilpowered.org
commands:
  anvil:
    description: Anvil root command
  callback:
    description: Anvil callback command
