name: Anvil
version: "${version}"
main: org.anvilpowered.anvil.spigot.AnvilSpigot
api-version: 1.15
description: A cross-platform Minecraft plugin framework
website: https://www.anvilpowered.org
commands:
  anvil:
    description: Anvil root command
  callback:
    description: Anvil callback command
